x-veld:
  executable:
    about:
      description: "cleans APIS NER data from whitespaces and minor noise."
      topic: 
        - "ETL"
        - "data sanitization"
    input:
      type: "folder"
      format: "json"
      content:
        - "gold data"
        - "NLP gold data"
        - "Named entity recognition gold data"
      path: /veld/input/
    output:
      -
        type: "folder"
        format: "json"
        content:
          - "gold data"
          - "NLP gold data"
          - "Named entity recognition gold data"
        path: /veld/output/a
      -
        type: "file"
        format: "txt"
        content: "log"
        path: /veld/output/clean.log

services:
  veld:
    build: .
    volumes:
      - ./clean.py:/veld/executable/clean.py
    command: python /veld/executable/clean.py
    environment:
      - PREFECT_API_URL=REPLACE_ME
      - DEPLOYMENT_NAME=REPLACE_ME
