x-veld:
  executable:
    about:
      description: "cleans APIS NER data from whitespaces and minor noise."
      topic: 
        - "ETL"
        - "data sanitization"
    input:
      path: /veld/input/
      format: "json"
      kind:
        - "Gold Data"
        - "NLP Gold Data"
        - "Named Entity Recognition Gold Data"
    output:
      a:
        path: /veld/output/a
        format: "json"
        kind:
          - "Gold Data"
          - "NLP Gold Data"
          - "Named Entity Recognition Gold Data"
      b:
        path: /veld/output/b
        format: "txt"
        kind: "log"

services:
  veld:
    build: .
    volumes:
      - ./clean.py:/veld/executable/clean.py
    command: python /veld/executable/clean.py
