x-veld:
  executable:
    about:
      description: "cleans APIS NER data from whitespaces and minor noise."
      topic: 
        - "ETL"
        - "data sanitization"
    input:
      type: "files"
      format: "json"
      content:
        - "gold data"
        - "NLP gold data"
        - "Named Entity Recognition gold data"
      path: /veld/input/
    output:
      a:
        type: "files"
        format: "json"
        content:
          - "Gold Data"
          - "NLP Gold Data"
          - "Named Entity Recognition Gold Data"
        path: /veld/output/a
      b:
        type: "files"
        format: "txt"
        content: "log"
        path: /veld/output/b

services:
  veld:
    build: .
    volumes:
      - ./clean.py:/veld/executable/clean.py
    command: python /veld/executable/clean.py
